---
title: "BYU-Idaho Github Course Pages"
output: html_document
---

Welcome to the BYU-I Math Department Github course page.  You will find links to courses that have github.io pages below.  All courses are maintained through the [byuistats github group](https://github.com/byuistats){target="blank"}. For now, these are generally the classes that J. Hathaway teaches.

### Statistics & Data Science Courses

#### Active

##### [CSE 150 - Data Intuition and Insight](https://byuistats.github.io/CSE150)

We also host the [supplemental readings for CSE 150](https://byuistats.github.io/BYUI_CSE150_StatBook/) which are largely taken from the Math 221 and Math 325 textbooks.

##### [CSE 250 - Data Science Programming](https://byuistats.github.io/CSE250-Course)

We host the [Python for Data Science book](https://byuidatascience.github.io/python4ds/) as well.

##### [M325 - Intermediate Statistics](https://byuistats.github.io/Statistics-Notebook/)

This is the course textbook. Updates are made more often at Garrett Saunders [repository](https://github.com/saundersg/Statistics-Notebook).

##### [M335 - Data Wrangling and Visualization](https://byuistats.github.io/M335/)

This course started in the fall of 2017.  Other teachers may host their material in our learning management system.

##### [CSE 451 - Big Data Programming and Analytics](https://github.com/BYUI451)

We are in draft mode for this course.  See the [course_guide](https://github.com/BYUI451/course_guide) repo for the syllabus.

##### [M488 - Statistical and Data Science Consulting](https://github.com/BYUIDSconsulting)

The course has been around for a few years.  We are modernizing it to handle the influx of data science students. You can see the syllabus in [the course organization](https://github.com/BYUIDSconsulting/course_guide/blob/main/syllabus.md).

##### [M498 - Data Science Internship](https://byuistats.github.io/M498R_DS/)

This pages contains the syllabus and some information to help with searching for an internship.  You can also find internship information at [byuidatascience.github.io](https://byuidatascience.github.io/internship.html)

##### [M499 - Data Science Senior Project](https://github.com/BYUIDSseniorproject)

Each data science major will complete a 3-credit senior project with one of the data science faculty.

##### [M221(ABC) - Introduction to Statistics](http://byuistats.github.io/M221/)

Our [course textbook is now hosted using bookdown](https://byuistats.github.io/BYUI_M221_Book/). This course is largely maintained in BYU-I's learning management system.  We have a few material items here for the faculty to use.  J. Hathaway stores some of his course items on his own [M221 page](https://byuistats.github.io/M221_hathaway/index.html)


#### Historical

These are courses that have been taught in the past but have not been updated.

##### [M330 - Engineering Statistics](http://byuistats.github.io/M330/)

David Palmer and J. Hathaway used a different texbook than the other Math 330 teachers.  We have both stopped using this textbook and the material of the course has changed a little since J. Hathaway taught it.  Don't anticipate updates anytime soon to this page.

#### Data Repository

This repository is public and is in draft form.  It is mostly data that is used in Math 221.  

* [Data](https://github.com/byuistats/data)
* [Brigham Young University - Idaahho Data Science Repository with public data](https://github.com/byuidatascience) (search for repos with the name `data4`)

#### Data Science Program 

Below are links to information about our data science program

- [BYUIDATASCINCE on GitHUB](byuidatascience.github.io)
- [Math Department page for DS](http://www.byui.edu/mathematics/student-resources/data-science)
- [BYUI DS Program page](http://www.byui.edu/catalog/#/programs/41PwqJ9RZ)
